D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py
D:\Python39\python.exe d:/Wuhan_Project/train.py